In [17]:
import pandas

df_x1=pandas.read_json('x1_matches_dataset.json', dtype={'match_id': int, 'match_uuid': 'string', 'num_players': int,
                                                        'map_type' : int, 'visibility' : int, 'duration' : str,
                                                        'has_relevant_water' : bool, 'wCiv': str, 'lCiv' : str,
                                                        'average_rating' : float, 'average_rating_normalized': float })

df_team=pandas.read_json('team_matches_dataset.json', dtype={'match_id': int, 'match_uuid': 'string', 'num_players': int,
                                                             'map_type' : int, 'visibility' : int, 'duration' : str,
                                                             'has_relevant_water' : bool, 'wCiv1': str, 'lCiv1' : str,
                                                             'average_rating' : float, 'average_rating_normalized': float,
                                                             'wCiv2' : str, 'lCiv2' : str, 'wCiv3' : str, 'lCiv3' : str,
                                                             'wCiv4' : str, 'lCiv4' : str})

df_civ=pandas.read_json('Civilization_Dataset.json', dtype={int})

In [29]:
df_civ=df_civ.astype('category')

In [26]:
df_x1['map_type']=df_x1['map_type'].astype('category')
df_x1['num_players']=df_x1['num_players'].astype('category')
df_x1['visibility']=df_x1['visibility'].astype('category')
df_x1['duration']=df_x1['duration'].astype('category')
df_x1['has_relevant_water']=df_x1['has_relevant_water'].astype('category')
df_x1['wCiv']=df_x1['wCiv'].astype('category')
df_x1['lCiv']=df_x1['lCiv'].astype('category')
df_x1.dtypes

map_type                     category
match_id                        int64
match_uuid                     object
num_players                  category
visibility                   category
duration                     category
has_relevant_water           category
wCiv                         category
lCiv                         category
average_rating                float64
average_rating_normalized     float64
dtype: object

In [27]:
df_team['map_type']=df_team['map_type'].astype('category')
df_team['num_players']=df_team['num_players'].astype('category')
df_team['visibility']=df_team['visibility'].astype('category')
df_team['duration']=df_team['duration'].astype('category')
df_team['has_relevant_water']=df_team['has_relevant_water'].astype('category')
df_team['wCiv1']=df_team['wCiv1'].astype('category')
df_team['wCiv2']=df_team['wCiv2'].astype('category')
df_team['wCiv3']=df_team['wCiv3'].astype('category')
df_team['wCiv4']=df_team['wCiv4'].astype('category')
df_team['lCiv1']=df_team['lCiv1'].astype('category')
df_team['lCiv2']=df_team['lCiv2'].astype('category')
df_team['lCiv3']=df_team['lCiv3'].astype('category')
df_team['lCiv4']=df_team['lCiv4'].astype('category')

df_team.dtypes

map_type                     category
match_id                        int64
match_uuid                     object
num_players                  category
visibility                   category
duration                     category
has_relevant_water           category
wCiv1                        category
wCiv2                        category
wCiv3                        category
wCiv4                        category
lCiv1                        category
lCiv2                        category
lCiv3                        category
lCiv4                        category
average_rating                float64
average_rating_normalized     float64
dtype: object

In [24]:
df_x1

,map_type,match_id,match_uuid,num_players,visibility,duration,has_relevant_water,wCiv,lCiv,average_rating,average_rating_normalized
0,9,40745268,771f9279-8792-be44-bf32-5db278f358aa,2,0,short,False,Byzantines,Magyars,1234.0,0.464965
1,9,40745265,15f45199-5ce5-2247-a421-9f6cc28afa72,2,0,short,False,Incas,Britons,1111.0,0.409895
2,9,40745258,5b9697b8-366d-8748-a967-c34722ffe377,2,0,short,False,Ethiopians,Mayans,1202.5,0.450862
3,9,40745189,40d77d0b-b08c-f945-883e-3fccc7b1b8a4,2,0,medium,False,Mayans,Franks,1453.0,0.563018
4,9,40745343,3b1f86e3-85d4-7248-912b-1506c1d0f44b,2,0,short,False,Magyars,Vikings,1167.0,0.434968
...,...,...,...,...,...,...,...,...,...,...,...
20876,16,42259177,84b0b3f9-cd2a-8f4a-b969-8e055f884f6f,2,0,short,False,Vikings,Cumans,1178.5,0.440116
20877,9,42259167,3e33efe4-02c4-c34f-b47c-f5097b2eae19,2,0,short,False,Chinese,Chinese,1692.5,0.670248
20878,9,42259216,fbf6ea6a-08ff-d746-8403-f4f45d932b15,2,0,medium,False,Byzantines,Incas,926.5,0.327289
20879,29,42259211,fba9486f-1954-6b4f-a37f-d9b55012de9c,2,0,short,False,Franks,Mongols,1103.0,0.406313
20880,87,42259214,a5247657-5067-3c47-96f0-0dc3a834063d,2,0,short,False,Franks,Goths,1297.5,0.493396